### ISSUE TITLE
有两个疑问

### ISSUE THREAD

**Issue by HannyYaung** [YiiGuxing/CompositionAvatar#1]
好绚丽的控件，能不能支持网络加载图片，能不能给个具体注释，看起来有点难

**Comment by YiiGuxing** [comment]
@HannyYaung 注释和文档以后都会加的。至于网络加载图片，这个需要自己实现，sample上就有一个简单的例子，在 [`BindingUtil`](https://github.com/YiiGuxing/CompositionAvatar/blob/master/sample/src/main/java/cn/yiiguxing/sample/BindingUtil.java) 类里面。
